# Use a base image that includes Node.js and npm
FROM node:latest

# Set the working directory for backend
WORKDIR /app/quirknotes/backend

# Copy backend package files
COPY quirknotes/backend/package*.json ./

# Install backend dependencies
RUN npm install

# Copy backend source code
COPY quirknotes/backend ./

# Command to start nginx and serve frontend
CMD ["npm", "run", "dev"]
