# Use a base image that includes Node.js and npm
FROM node:latest

# Set the working directory for backend
WORKDIR /app/quirknotes/backend

# Copy backend package files
COPY quirknotes/backend/package*.json ./

# Install backend dependencies
RUN npm install

# Copy backend source code
COPY quirknotes/backend ./

# Build backend
RUN npm run dev

# Use a base image that includes MongoDB
FROM mongo:latest

# Expose the port the app runs on
EXPOSE 4000

# Command to run the MongoDB server when the container starts
CMD ["mongod", "--dbpath=data/db"]
